[phases.setup]
aptPkgs = ["python3", "python3-pip", "ffmpeg"]

[phases.install]
cmds = [
  "npm install",
  "curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o /usr/local/bin/yt-dlp",
  "chmod a+rx /usr/local/bin/yt-dlp"
]

[start]
cmd = "node server.js"
